config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'groups#index'

  resources :groups do
    resources :certs, :shallow => true do
      resources :claimants, :shallow => true
    end
  end

  resources :providers
  resources :refunds
  resources :users

  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get '/log-out' => 'sessions#destroy', as: :log_out
end

app/models/cert.rb
class Cert < ActiveRecord::Base
  belongs_to :group
  has_many :claimants
  validates :cert_number, :presence => true
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :member_id, :presence => true
end

app/models/claimant.rb
class Claimant < ActiveRecord::Base
  belongs_to :cert
  has_many :refunds
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :claimant_number, :presence => true
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :certs
  validates :group_number, :presence => true
  validates :name, :presence => true
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  has_many :refunds
  validates :name, :presence => true
  validates :phone, :presence => true
  validates :tin, :presence => true

  def self.search(provider)
    if provider
      find_by(tin: "%#{provider}%")
    else
      scoped
    end
  end
end

app/models/refund.rb
class Refund < ActiveRecord::Base
  belongs_to :provider
  belongs_to :claimant
  validates :amount_requested, :presence => true
  validates :reason, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/certs_controller.rb
class CertsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]

  def new
    @group = Group.find(params[:group_id])
    @cert = @group.certs.new
  end

  def show
    @cert = Cert.find(params[:id])
    @claimants = @cert.claimants.all
  end

  def create
    @group = Group.find(params[:group_id])
    @cert = @group.certs.new(cert_params)
    if @cert.save
      @claimant = @cert.claimants.create(:first_name => @cert.first_name, :last_name => @cert.last_name, :claimant_number => '001')
      respond_to do |format|
        format.html { redirect_to group_path(@cert.group) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end
  end

private
  def cert_params
    params.require(:cert).permit(:cert_number, :first_name, :last_name, :member_id)
  end
end

app/controllers/claimants_controller.rb
class ClaimantsController < ApplicationController

  def index

  end

  def show
    @claimant = Claimant.find(params[:id])
  end

  def new
    @cert = Cert.find(params[:cert_id])
    @claimant = @cert.claimants.new
  end

  def create
    @cert = Cert.find(params[:cert_id])
    @claimant = @cert.claimants.new(claimant_params)
    if @claimant.save
      respond_to do |format|
        format.html { redirect_to cert_path(@claimant.cert) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end
  end

private
  def claimant_params
    params.require(:claimant).permit(:claimant_number, :first_name, :last_name)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      respond_to do |format|
        format.html { redirect_to groups_path }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end
  end

  def show
    @group = Group.find(params[:id])
    @certs = @group.certs.all
  end

private
  def group_params
    params.require(:group).permit(:name, :group_number)
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
  
  def index
    @providers = Provider.all
  end

  def new
    @provider = Provider.new
  end

  def create
    @provider = Provider.new(provider_params)
    if @provider.save
      respond_to do |format|
        format.html { redirect_to providers_path }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end
  end

  def show
    @provider = Provider.find(params[:id])
  end

private
  def provider_params
    params.require(:provider).permit(:name, :phone, :tin)
  end
end

app/controllers/refunds_controller.rb
class RefundsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  
  def index
    @refunds = Refund.all
  end

  def new
    @refund = Refund.new
    @providers = Provider.find_by(tin: params[:provider])
    @provider = Provider.new
  end

  def create
    @refund = Refund.new(refund_params)
    if @refund.save
      flash[:notice] = "The refund was successfully added"
      redirect_to refunds_path
    else
      render :new
    end
  end

  def show
    @refund = Refund.find(params[:id])
  end

  def edit
    @refund = Refund.find(params[:id])
    @providers = Provider.all
    @claimants = Claimant.all 
  end

  def update
    @refund = Refund.find(params[:id])
    if @refund.update(refund_params)
      flash[:success] = "Refund updated successfully"
      redirect_to refunds_path
    else
      render :edit
    end
  end

private
  def refund_params
    params.require(:refund).permit(:provider_id, :claimant_id, :amount_requested, :reason)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end
 
  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/views/certs/_cert.html.erb
<li><%= cert.cert_number %> | <%= link_to cert.last_name + ", " + cert.first_name, cert_path(cert) %></li>

app/views/certs/_form.html.erb
<%= form_for [@group, @cert], remote: true do |f| %>
  <%= f.label :cert_number %>
  <%= f.text_field :cert_number %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :member_id %>
  <%= f.text_field :member_id %>
  <%= f.submit %>
<% end %>

app/views/certs/create.js.erb
$('#new_cert').remove();
$('#new-cert').show();
$('#cert-list').append('<%= j render @cert %>');

app/views/certs/new.html.erb
<h1>New Member</h1>

<%= render 'form' %>

app/views/certs/new.js.erb
$('#new-cert').hide().after('<%= j render "form" %>');

app/views/certs/show.html.erb
<%= link_to "Return to Group", group_path(@cert.group_id) %>
<h3><%= @cert.first_name %> <%= @cert.last_name %></h3>

<%= link_to "New Claimant", new_cert_claimant_path(@cert), id: "new-claimant", remote: true %>


<ul class="lead" id="claimant-list">
  <%= render @claimants %>
</ul>

app/views/claimants/_claimant.html.erb
<li><%= claimant.claimant_number %> | <%= link_to claimant.first_name + " " + claimant.last_name, claimant_path(claimant) %></li>

app/views/claimants/_form.html.erb
<%= form_for [@cert, @claimant] do |f| %>
  <%= f.label :claimant_number %>
  <%= f.text_field :claimant_number %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.submit %>
<% end %>

app/views/claimants/new.html.erb
<h1>New Claimant</h1>

<%= render 'form' %>

app/views/claimants/new.js.erb
$('#new-claimant').hide().after('<%= j render "form" %>');

app/views/claimants/show.html.erb
<%= link_to "Return to Cert", cert_path(@claimant.cert_id) %>
<h3><%= @claimant.first_name %> <%= @claimant.last_name %></h3>

<%= @claimant.claimant_number %>

app/views/groups/_form.html.erb
<%= form_for @group, remote: true do |f| %>
  <%= f.label :group_number, "Group Number" %>
  <%= f.text_field :group_number %>
  <%= f.label :name, "Group Name" %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/groups/_group.html.erb
<li><%= group.group_number %> | <%= link_to group.name, group_path(group) %></li>

app/views/groups/create.js.erb
$('#new_group').remove();
$('#new-group').show();
$('#group-list').append('<%= j render @group %>');

app/views/groups/groups.html.erb
<h1>Groups</h1>

<ul class='lead list-unstyled'>
  <% @groups.each do |group| %>
    <li><%= group.group_number %> | <%= link_to group.name, group_path(group) %></li>
  <% end %>
</ul>

<p>
  <%= link_to 'Add a new group', new_group_path(@group) %>
</p>

app/views/groups/index.html.erb
<h1>Groups</h1>

<%= link_to 'Add a new group', new_group_path(@group), id: "new-group", remote: true %>

<ul class='lead list-unstyled' id='group-list'>
  <%= render @groups %>
</ul>

app/views/groups/new.html.erb
<h1>Add a New Group</h1>

<% if @group.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @group.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'form' %>

app/views/groups/new.js.erb
$('#new-group').hide().after('<%= j render "form" %>');

app/views/groups/show.html.erb
<%= link_to "Return to Group Page", groups_path %>
<h1><%= @group.name %></h1>

<p>
  <%= @group.group_number %>
</p>

<%= link_to "New Member", new_group_cert_path(@group), id: "new-cert", remote: true %>

<ul class="lead list-unstyled" id="cert-list">
  <%= render @certs %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand">EBMS Dashboard</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if current_page?(groups_path) %>"><%= link_to 'Home', groups_path %></li>
          <li class="<%= 'active' if current_page?(new_refund_path) %>"><%= link_to 'New Refund Request', new_refund_path(@groups) %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><span class="navbar-text">Welcome, <%= current_user.email %></span></li>
            <li><button type="button" class="btn btn-default navbar-btn"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></button></li>
          <% else %>
            <li><button type="button" class="btn btn-default navbar-btn"><%= link_to 'Sign in', new_user_session_path %></button></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <div>
      <%= flash_messages %>
    </div>
    <%= yield %>
  </div>
</body>
</html>

app/views/providers/_form.html.erb
<%= form_for @provider, remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <%= f.label :tin %>
  <%= f.text_field :tin %>
  <%= f.submit %>
<% end %>

app/views/providers/_provider.html.erb
<div id="add-provider">
  <% if @providers %>
    <%= @providers.name %>
  <% else %>
    <%= link_to "New Provider", new_provider_path, id: "new-provider", remote: true %>
  <% end %>
</div>

app/views/providers/create.js.erb
$('#new_provider').remove();
$('#new-provider').show();
$('#add-provider').append('<%= j render @provider %>');

app/views/providers/index.html.erb
<h1>Providers</h1>

<ul class='lead list-unstyled'>
  <% @providers.each do |provider| %>
    <li><%= link_to provider.name, provider_path(provider) %> - <%= provider.tin %></li>
  <% end %>
</ul>

app/views/providers/new.html.erb
<h1>Add a New Provider</h1>

<%= render 'form' %>

app/views/providers/new.js.erb
$('#add-provider').hide().after('<%= j render "form" %>');

app/views/providers/show.html.erb
<h1><%= @provider.name %></h1>

<p>
  TIN Number: <%= @provider.tin %>
</p>
<p>
  Phone Number: <%= @provider.phone %>
</p>

app/views/refunds/_form.html.erb
<%= form_tag new_refund_path, remote: true, :method => 'get' do %>
  <p>
    <%= text_field_tag :provider, params[:provider], placeholder: "Enter Provider TIN" %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<%= render @provider %>

<% if @new_provider %>
<%= @new_provider.name %> 'here is the shit'
<% end %>
<%= form_for @refund do |f| %>
  <div class="col-md-5">
    <div class="form-group">
      <%= f.label :amount_requested %>
      <%= f.number_field :amount_requested, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :reason %>
      <%= f.text_area :reason, class: "form-control" %>
    </div>

    <%= f.submit "Submit", class: 'btn btn-default' %>
  </div>
<% end %>

app/views/refunds/edit.html.erb
<h1>Edit Refund</h1>

<%= render 'form' %>

app/views/refunds/index.html.erb
<h1>All Outstanding Refunds</h1>

<ul class="lead list-unstyled">
  <% @refunds.each do |refund| %>
    <li><%= refund.id %> - <%= number_to_currency(refund.amount_requested) %> - <%= refund.provider.name %> - <%= refund.claimant.first_name %> <%= refund.claimant.last_name %> <%= link_to "Edit", edit_refund_path(refund) %></li>
  <% end %>
</ul>

app/views/refunds/new.html.erb
<h1>Add a New Refund</h1>

<%= render 'form' %>

app/views/refunds/show.html.erb
<h1>Refund Detail</h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for User.new do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>